### ISSUE TITLE
Support GeoIP maxmind

### ISSUE THREAD

**Issue by parsa97** [mosajjal/dnsmonster#102]
This feature is useful for get geolocation information from DNS requests using MaxMind databases. 

Like the output with at least the following fields:

```
Continent
CountryISOCode
City
AS Number
AS Owner
```
PR: #105

**Comment by mosajjal** [comment]
hey mate. at this stage I'm not keen to add additional context and processors to `dnsmonster`. in my opinion, enrichment needs to sit at the ETL layer (if you're using Kafka) or as a correlation lookup table (in Elastic/Splunk setup). 

the reason behind rejecting this idea is as follows:
  - since `dnsmonster` provides source and destination IP masking, the Maxmind integration either defeats the purpose of the privacy-focus of dnsmonster, or makes the geolocation metadata inaccurate
  - maxmind mmdb lookup is not a negligible latency at scale. a feature that relies on a database lookup per IPv4/IPv6, can limit how much ingestion can be done by the agent. I understand the proposal being an optional feature, but nonetheless it'll complicate the design even more. 

hope that makes sense.

**Comment by parsa97** [comment]
Regarding the privacy aspect, I understand it's a complex issue that can be sensitive. If privacy concerns aren't a blocker for this discussion, I'm keen to focus on the performance considerations.

I've conducted tests with GeoIP and without, and the difference in performance was negligible. For instance, based on a large pcap file:
```
#capinfos:
Encapsulation = Raw IP (7 - rawip)
Capture length = 65536
Time precision = microseconds (6)
Time ticks per second = 1000000
Number of stat entries = 0
Number of packets = 3668278
```

I've analyzed memory and CPU profiles, and from what I observed, the performance impact is quite acceptable. Considering the benefits it brings, I believe the trade-off is worthwhile.

If you're open to it, I'd like to discuss further how we can optimize and fine-tune this integration to ensure minimal impact on dnsmonster's core functionalities.

[mem-geoip pprof](https://github.com/mosajjal/dnsmonster/assets/14282926/42c7c467-4bba-4889-937b-cfff274c63a2)
[cpu-geoip pprof](https://github.com/mosajjal/dnsmonster/assets/14282926/857b91b4-5513-49b7-b93a-8d83ee97aa89)
[mem pprof](https://github.com/mosajjal/dnsmonster/assets/14282926/8db92150-7f27-4b9d-bea4-649be9d5e29f)
[cpu pprof](https://github.com/mosajjal/dnsmonster/assets/14282926/7591ee87-ba97-4921-8b1b-ae5eeae04b34)
[pprof.zip](https://github.com/user-attachments/files/16040057/pprof.zip)

**Comment by mosajjal** [comment]
not something I'm keen on adding at this point in time. I have a plan to revamp and refactor dnsmonster for a v2 release with a better plugin system (much like coredns). this could live in that realm. closing for now.
