### ISSUE TITLE
how to make dns-monster listen multiple ports

### ISSUE THREAD

**Issue by HesaMtiPu** [mosajjal/dnsmonster#47]
Hello !!
hope you are doing well.
how to make dns-monster listen multiple ports ???

**Comment by HesaMtiPu** [comment]
We have configured DoH and Dot in our DNS.
so we want to listen 853 ports as well.

**Comment by mosajjal** [comment]
for now it's impossible to have multiple `--port`` options. I'm planning to remove that option altogether and only rely on `bpf` for packet filtering. 

keep in mind that the traffic on port 853 won't be captured anyway since it's encrypted. You might be better off leveraging `dnstap` logging in your DNS server for both `53` and `853` and capture logs that way.
